// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVNbMyR1U-tgz69iepTnoqpPv-r_LkP-4',
    appId: '1:790267224153:web:f5f30178b662ced1991148',
    messagingSenderId: '790267224153',
    projectId: 'bloom-5384c',
    authDomain: 'bloom-5384c.firebaseapp.com',
    storageBucket: 'bloom-5384c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG8l6Mz248aB6wmr-YdrpbRiZMdR8mTOg',
    appId: '1:790267224153:android:45e087d73450cfd6991148',
    messagingSenderId: '790267224153',
    projectId: 'bloom-5384c',
    storageBucket: 'bloom-5384c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeVLYR2lH3nghKR0hO0S0JHWlwgVws6zQ',
    appId: '1:790267224153:ios:7eb9320dfc5df827991148',
    messagingSenderId: '790267224153',
    projectId: 'bloom-5384c',
    storageBucket: 'bloom-5384c.appspot.com',
    iosBundleId: 'com.example.vyder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeVLYR2lH3nghKR0hO0S0JHWlwgVws6zQ',
    appId: '1:790267224153:ios:7eb9320dfc5df827991148',
    messagingSenderId: '790267224153',
    projectId: 'bloom-5384c',
    storageBucket: 'bloom-5384c.appspot.com',
    iosBundleId: 'com.example.vyder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVNbMyR1U-tgz69iepTnoqpPv-r_LkP-4',
    appId: '1:790267224153:web:4a33c0dcfc8ac150991148',
    messagingSenderId: '790267224153',
    projectId: 'bloom-5384c',
    authDomain: 'bloom-5384c.firebaseapp.com',
    storageBucket: 'bloom-5384c.appspot.com',
  );
}
